name: Issue needs triage
description: Add Needs Triage label to new issues
resource: repository

configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issue
          - isAction:
              action: 'opened'
          - not:
              - isPartOfProject
          - not:
              - isAssignedToSomeone
          - not:
              - isLabeled
        then:
          - addLabel:
              label: 'Needs: Triage 🔍'
