name: PR needs review
description: Assign Needs Review label to new/updated PRs
resource: repository

configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
          - prTargetsBranch:
              branchName: main
          - isOpen
          - or:
              - isAction:
                  action: review_requested
              - isAction:
                  action: synchronize
        then:
          - addLabel:
              label: 'Needs: Triage 🔍'
